# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('idadmon', models.IntegerField(primary_key=True, serialize=False)),
                ('pnombre', models.CharField(max_length=25)),
                ('snombre', models.CharField(max_length=25)),
                ('papellido', models.CharField(max_length=25)),
                ('sapellido', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=25)),
                ('contra', models.CharField(max_length=25)),
                ('genero', models.CharField(max_length=25)),
            ],
        ),
    ]
