# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='estado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='egresado',
            name='estado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
