# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20171017_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='idegresado',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
