# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20171017_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='correo',
            field=models.EmailField(max_length=50),
        ),
    ]
